name: quality

on: push

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install npm dependencies
        run: npm ci
        env:
          HUSKY: 0
      - name: Run quality checks
        run: npm run quality
